[package]
name = "discord_bot"
version = "0.1.0"
edition = "2024"

[profile.opt_heavy]
lto = true
codegen-units = 1
strip = true
inherits = "release"

[dependencies]
dotenvy = "0.15.7"
poise = "0.6.1"
rand = "0.9.2"
tokio = { version = "1.48.0", features = ["full"] }
